version: '3.8'
services:
#  adonis_app:
#    container_name: adonis_app
#    build:
#      context: .
#    volumes:
#      - .:/home/node/app
#    ports: 
#      - 3333:3333
#    depends_on:
#      - database

#  adminer:
#      image: adminer:latest
#      restart: always
#      ports:
#        - 8080:8080
#      depends_on:
#        - database

  database:
    container_name: admbp_sql
    image: postgres:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "${PG_PORT}:5432"
    expose:
      - ${PG_PORT}
    environment:
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_DATABASE: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_TCP_PORT: ${PG_PORT}

    volumes:
      # - ./database/docker/container_postgres:/var/lib/postgres
      - ${MSSQL_DATA_CONTAINER}